bot:
  token: # Добавьте API токен вашего бота
  target-channel: # Добавьте id вашего канала (например, @telegchannelid)
vk:
  access-token: # Добавьте ключ доступа вашей группы
  group-id: # Добавьте id вашей группы
